name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: one-line script
        shell: cmd
        run: |
          cd scripts
          windows.bat
      #- name: Upload windows artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    path: scripts/ubuntu/aseprite-linux64.deb
