name: CI
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: one-line script
        shell: cmd
        run: |
          cd scripts
          windows.bat
      - name: Upload windows artifact
        uses: actions/upload-artifact@v2
        with:
          path: scripts/Windows/aseprite-win64.zip
