name: Get latest release version
on:
  watch:
  push:
    types: [started]
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/aseprite/aseprite/releases/latest | jq -r ".tag_name" > release-versions/version.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v1.4.1
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: true
          git_committer_name: Insouciant21
          git_committer_email: ${{ secrets.owner_email }}
      - name: config
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.email ${{ secrets.owner_email }}
          git config --global user.name "Insouciant21"
          git add .
          git commit -m "New release version"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Repository Dispatch
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.work1 }}
          event-type: new-release
