name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled files
        run: |
          wget https://github.com/Insouciant21/action_aseprite/releases/latest/download/aseprite-linux.zip
          7z x aseprite-linux.zip -y -oaseprite
      - run: curl -sL https://api.github.com/repos/aseprite/aseprite/releases/latest | jq -r ".tag_name"
        id: ver
      - name: Write control info
        run: |
          sudo apt install tree
          mkdir usr
          mkdir usr/share
          mkdir usr/share/aseprite
          cd aseprite/
          mkdir DEBIAN
          echo "package: Aseprite" > DEBIAN/control
          echo "version: ${{ steps.ver.outputs.ase_ver }}" >> DEBIAN/control
          echo "architecture: amd64" >> DEBIAN/control
          echo "maintainer: Daivd Capello" >> DEBIAN/control
          echo "description: Animated sprite editor & pixel art too" >> DEBIAN/control
          cd ..
          mv aseprite/* usr/share/aseprite/
          mv usr/ aseprite/
          mv aseprite/usr/share/aseprite/DEBIAN/ aseprie/DEBIAN/
          sudo dpkg -b aseprite aseprite-linux.deb
          curl -sL https://git.io/file-transfer | sh 
          ./transfer wet aseprite-linux.deb
          
          
          
