name: Mac #1
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: clone aseprite source
      run: git clone --recursive https://github.com/aseprite/aseprite.git
    - name: download skia
      run: |
        curl -o skia.zip 'https://github.com/aseprite/skia/releases/download/m81-b607b32047/Skia-macOS-Release-x64.zip'
        brew install p7zip
        7z x skia.zip -y -oskia
    - name: Compiling aseprite for macos
      run: |
        cd aseprite
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -DLAF_BACKEND=skia -DSKIA_DIR=../../skia -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64 -G Ninja ..
        ninja aseprite
    - name: archive bin
      run: |
        cd aseprite/build/bin
        7z -tzip a aseprite-linux.zip *
        cd ../../..
        mv aseprite/build/bin/aseprite-macos.zip .
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
          path: aseprite-macos.zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: test
          release_name: aseprite v0.0.0-alpha
          draft: false
          body: |
            Unofficial dev release.
            Support aseprite author at https://www.aseprite.org
          prerelease: true
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: aseprite-macos.zip
          asset_name: aseprite-macos.zip
          asset_content_type: application/zip
        
