# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "::set-output name=action_ase::$(curl -s https://api.github.com/repos/aseprite/aseprite/releases/latest | grep browser_download_url | grep aseprite | cut -d '"' -f 4)"
      id: ase
    - name: Clone aseprite source
      run: |
        brew install p7zip ninja
        wget -O source.zip ${{ steps.ase.outputs.action_ase }}
        7z x source.zip -y -oaseprite
    - name: Download compiled skia
      run: |
        wget -O skia.zip 'https://github.com/aseprite/skia/releases/download/m81-b607b32047/Skia-macOS-Release-x64.zip'
        7z x skia.zip -y -oskia
    - name: Compiling aseprite for macos
      run: |
        cd aseprite
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -DLAF_BACKEND=skia -DSKIA_DIR=../../skia -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64 -G Ninja ..
        ninja aseprite
    - name: Archive bin
      run: |
        cd aseprite/build/bin
        7z -tzip a aseprite-macos.zip * -mx0
        cd ../../..
        mv aseprite/build/bin/aseprite-macos.zip .
    - name: Upload macos artifact
      uses: actions/upload-artifact@v2
      with:
          path: aseprite-macos.zip
